### ISSUE TITLE
[MO] No module named 'mo' on pytorch convertion tests

### ISSUE THREAD

**Issue by alvoron** [openvinotoolkit/openvino_contrib#257]
@dkurt @likholat could you please fix it?

```
Traceback (most recent call last):
  File "run_tests.py", line 14, in <module>
    import mo_pytorch
  File "/agent/_work/1/openvino_contrib/modules/mo_pytorch/mo_pytorch.py", line 23, in <module>
    import mo
ModuleNotFoundError: No module named 'mo'

```
https://dev.azure.com/openvinoci/dldt/_build/results?buildId=226371&view=logs&j=9df09860-c2bf-529a-b3cd-66c2937309a0&t=ec4ea673-ce77-5db0-f201-368afd76cfd5&l=224

**Comment by dkurt** [comment]
Fix is here: #258
