### ISSUE TITLE
model conversion failed in mo_pytorch.py for fasterrcnn_resnet50_fpn

### ISSUE THREAD

**Issue by CameronVetter** [openvinotoolkit/openvino_contrib#356]
I've trained a model based on Mask-RCNN with a ResNet50 backbone but trained on a custom dataset similar to #271  .  I've attempted to follow the example in https://github.com/openvinotoolkit/openvino_contrib/modules to convert this directly into an openvino model.  My code looks like this:

```
# Create model
model = torch.jit.load('model.pt')
model.eval()

# Convert to OpenVINO IR
import mo_pytorch
mo_pytorch.convert(model, input_shape=[1, 3, 800, 800], model_name='Mask_RCNN',
                   scale=255,
                   reverse_input_channels=True)
```

Originally I tried this with the latest and greatest versions of PyTorch V 1.11.0+cu102 and TorchVision V 0.12.0+cu102, but once I encountered this error I switched to the versions PyTorch V 1.9.0+cu102 and TorchVision V 0.10.0+cu102 due to others implying this was the "tested" version.  With either version when I run this code I get the model conversion failed error with the following debug information:

```
        - Path for generated IR:        /home/cameron/convert_to_vino/.
        - IR output name:       Mask_RCNN
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1, 3, 800, 800]
        - Source layout:        Not specified
        - Target layout:        Not specified
        - Layout:       Not specified
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         255.0
        - Precision of IR:      FP32
        - Enable fusing:        True
        - User transformations:         Not specified
        - Reverse input channels:       True
        - Enable IR generation for fixed input shape:   False
        - Use the transformations config file:  None
Advanced parameters:
        - Force the usage of legacy Frontend of Model Optimizer for model conversion into IR:   False
        - Force the usage of new Frontend of Model Optimizer for model conversion into IR:      False
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID (<class 'mo_extensions.load.pytorch.loader.PyTorchLoader'>)": no implementation found for '.forward' on types that implement __torch_function__: [OpenVINOTensor]
[ ERROR ]  Traceback (most recent call last):
  File "/home/cameron/convert_to_vino/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/utils/class_registration.py", line 278, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "/home/cameron/convert_to_vino/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/middle/pattern_match.py", line 46, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/home/cameron/convert_to_vino/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/load/loader.py", line 14, in find_and_replace_pattern
    self.load(graph)
  File "/home/cameron/openvino_contrib/modules/mo_pytorch/mo_extensions/load/pytorch/loader.py", line 96, in load
    model(inputs['input'])
  File "/home/cameron/convert_to_vino/openvino_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: no implementation found for '.forward' on types that implement __torch_function__: [OpenVINOTensor]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cameron/convert_to_vino/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "/home/cameron/convert_to_vino/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 489, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/home/cameron/openvino_contrib/modules/mo_pytorch/mo_pytorch.py", line 99, in _prepare_ir
    graph = unified_pipeline(argv)
  File "/home/cameron/convert_to_vino/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/pipeline/unified.py", line 13, in unified_pipeline
    class_registration.apply_replacements(graph, [
  File "/home/cameron/convert_to_vino/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/utils/class_registration.py", line 328, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "/home/cameron/convert_to_vino/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/utils/class_registration.py", line 314, in apply_replacements_list
    apply_transform(
  File "/home/cameron/convert_to_vino/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/utils/logger.py", line 112, in wrapper
    function(*args, **kwargs)
  File "/home/cameron/convert_to_vino/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/utils/class_registration.py", line 302, in apply_transform
    raise Exception('Exception occurred during running replacer "{} ({})": {}'.format(
Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'mo_extensions.load.pytorch.loader.PyTorchLoader'>)": no implementation found for '.forward' on types that implement __torch_function__: [OpenVINOTensor]

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
```

I've tried loading the model and performing a prediction and the model does function as expected, so I do not believe anything is wrong with the model.  Since there is no example and / or details beyond the couple lines of code in the readme, I'm not certain what the actual torchvision version is that I should be targeting or the openvino version I should choose.  The version of OpenVino I'm targeting is 2022.1.0.643.

**Comment by dkurt** [comment]
Hi! Can you please share a model so we can reproduce issue locally? Even with randomly initialized weights.

**Comment by CameronVetter** [comment]
I'm unsure of the best way to share the model in a github issue, so I've uploaded it here: [https://1drv.ms/u/s!AofkugmEOKADh_QZvQU0bWQm2kfOcQ?e=7GxEh9](https://1drv.ms/u/s!AofkugmEOKADh_QZvQU0bWQm2kfOcQ?e=7GxEh9)

This is the exact model I'm using to reproduce this locally.

**Comment by dkurt** [comment]
@CameronVetter, Currently module does not support TorchScript models conversion, so can you please try this code?

```python
import torch
import torchvision.models as models

model_jit = torch.jit.load('github356_model.pt', map_location=torch.device("cpu"))
model = models.detection.mask_rcnn.maskrcnn_resnet50_fpn(num_classes=2)
model.load_state_dict(model_jit.state_dict())
model.eval()

# Convert to OpenVINO IR
import mo_pytorch
mo_pytorch.convert(model, input_shape=[1, 3, 800, 800], model_name='Mask_RCNN',
                   scale=255,
                   reverse_input_channels=True)
```
I used PyTorch 1.9.1 and Torchvision 0.10.0

**Comment by CameronVetter** [comment]
Thank you, that example worked well.  I will just skip TorchScript in the future, I did not realize that was unsupported.
