### ISSUE TITLE
[Java API 2.0]GetCore: Failed to find plugins.xml file in arm Android application.

### ISSUE THREAD

**Issue by IRONICBo** [openvinotoolkit/openvino_contrib#420]
Hello, When I use Java API 2.0 `new Core()` in android application, It seems that the application went wrong and shows that it can't find the plugins.xml file in my application.

That means I need to load the `plugins.xml` file to specific  path?

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.intel.openvino, PID: 3283
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: java.lang.Exception: 
    InferenceEngineException: 
    	GetCore: Failed to find plugins.xml file
        at org.intel.openvino.Core.GetCore(Native Method)
        at org.intel.openvino.Core.<init>(Core.java:20)
        at org.intel.openvinodemo.MainActivity.processNetwork(MainActivity.java:107)
        at org.intel.openvinodemo.MainActivity.onRequestPermissionsResult(MainActivity.java:196)
        at android.app.Activity.requestPermissions(Activity.java:5297)
        at org.opencv.android.CameraActivity.onStart(CameraActivity.java:42)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1467)
        at android.app.Activity.performStart(Activity.java:8079)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3666)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2212)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7798)
```

**Comment by IRONICBo** [comment]
The old Java API 1.0 `IECore()` support to get plugins.xml from config，but the new API can not read the plugins.xml in `Core()`.

 
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/47499836/188262516-7c33e535-a154-443f-869b-91b2ea53edc0.png">

So in Android app, It is hard to  move the plugins.xml to arm64-v8a folder.

**Comment by IRONICBo** [comment]
Thanks for your PR, I have build the latest version of java api, but the `GetCore1()` function has been implemented in latest openvino? I use the new java api, but it show that the jni function can not find the right function.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.intel.openvino, PID: 12039
    java.lang.UnsatisfiedLinkError: No implementation found for long org.intel.openvino.Core.GetCore1(java.lang.String) (tried Java_org_intel_openvino_Core_GetCore1 and Java_org_intel_openvino_Core_GetCore1__Ljava_lang_String_2)
        at org.intel.openvino.Core.GetCore1(Native Method)
        at org.intel.openvino.Core.<init>(Core.java:24)
        at org.intel.openvinodemo.MainActivity.processNetwork(MainActivity.java:108)
        at org.intel.openvinodemo.MainActivity.onCreate(MainActivity.java:190)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Activity.performCreate(Activity.java:8034)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3798)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2212)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by likholat** [comment]
Please, make sure that:

1. you use the `master` branch of `openvino_contrib`
2. your fork is synced (my PR was merged today)
3. you didn't forgot to restart `openvino` build with uptated `openvino_contrib` branch:
   ```
   cmake -DCMAKE_BUILD_TYPE=Release \
      -DTHREADING=SEQ \
      -DIE_EXTRA_MODULES=/path/to/openvino_contrib/modules/java_api \
      -DBUILD_java_api=ON \
      -DANDROID_STL=c++_shared \
      -DENABLE_SAMPLES=OFF \
      -DENABLE_OPENCV=OFF \
      -DENABLE_CLDNN=OFF \
      -DENABLE_INTEL_VPU=OFF \
      -DENABLE_INTEL_GNA=OFF \
      -DENABLE_INTEL_MYRIAD=OFF \
      -DENABLE_TESTS=OFF \
      -DENABLE_GAPI_TESTS=OFF \
      -DENABLE_BEH_TESTS=OFF .. && make --jobs=$(nproc --all)
   ```

**Comment by IRONICBo** [comment]
> Please, make sure that:
> 
> 1. you use the `master` branch of `openvino_contrib`
> 2. your fork is synced (my PR was merged today)
> 3. you didn't forgot to restart `openvino` build with uptated `openvino_contrib` branch:
>    ```
>    cmake -DCMAKE_BUILD_TYPE=Release \
>       -DTHREADING=SEQ \
>       -DIE_EXTRA_MODULES=/path/to/openvino_contrib/modules/java_api \
>       -DBUILD_java_api=ON \
>       -DANDROID_STL=c++_shared \
>       -DENABLE_SAMPLES=OFF \
>       -DENABLE_OPENCV=OFF \
>       -DENABLE_CLDNN=OFF \
>       -DENABLE_INTEL_VPU=OFF \
>       -DENABLE_INTEL_GNA=OFF \
>       -DENABLE_INTEL_MYRIAD=OFF \
>       -DENABLE_TESTS=OFF \
>       -DENABLE_GAPI_TESTS=OFF \
>       -DENABLE_BEH_TESTS=OFF .. && make --jobs=$(nproc --all)
>    ```

Thanks, I have updated the openvino branch and rebuilt them, it worked well.
