### ISSUE TITLE
Unable to cross-compile ARM plugin for RPI Buster  - `fail 12 OpenVINO build failed`

### ISSUE THREAD

**Issue by YaroslavSchubert** [openvinotoolkit/openvino_contrib#429]
Hi :wave: I'm trying to cross-compile the ARM CPU plugin for Raspberry Pi Buster 32-bit using this tutorial [https://github.com/openvinotoolkit/openvino_contrib/wiki/How-to-build-ARM-CPU-plugin#approach-1-build-opencv-openvino-and-the-plugin-using-pre-configured-dockerfile-cross-compiling-the-preferred-way](https://github.com/openvinotoolkit/openvino_contrib/wiki/How-to-build-ARM-CPU-plugin#approach-1-build-opencv-openvino-and-the-plugin-using-pre-configured-dockerfile-cross-compiling-the-preferred-way).

The compilation got through the OpenCV successfully but stopped at OpenVino with the error:
`make: *** [Makefile:163: all] Error 2`

Last lines of the output:
```
cc1plus: warning: unrecognized command line option '-Wno-pessimizing-move'
cc1plus: warning: unrecognized command line option '-Wno-redundant-move'
arm-linux-gnueabihf-g++ -o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/libarm_compute_graph.so -Wl,--no-undefined -shared /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/DataLayerVisitor.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/Graph.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/GraphBuilder.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/GraphContext.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/GraphManager.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/INode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/INodeVisitor.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/PassManager.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/Tensor.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/TypeLoader.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/Utils.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/Workload.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/algorithms/TopologicalSort.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/backends/BackendRegistry.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/detail/CrossLayerMemoryManagerHelpers.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/detail/ExecutionHelpers.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/frontend/Stream.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/frontend/SubStream.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/mutators/DepthConcatSubTensorMutator.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/mutators/GroupedConvolutionMutator.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/mutators/InPlaceOperationMutator.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/mutators/MutatorUtils.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/mutators/NodeExecutionMethodMutator.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/mutators/NodeFusionMutator.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/mutators/SplitLayerSubTensorMutator.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/mutators/SyntheticDataTypeMutator.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/ActivationLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/ArgMinMaxLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/BatchNormalizationLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/BoundingBoxTransformLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/ChannelShuffleLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/ConcatenateLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/ConstNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/ConvolutionLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/DeconvolutionLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/DepthToSpaceLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/DepthwiseConvolutionLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/DequantizationLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/DetectionOutputLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/DetectionPostProcessLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/DummyNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/EltwiseLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/FlattenLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/FullyConnectedLayer.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/FusedConvolutionBatchNormalizationNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/FusedConvolutionBatchNormalizationWithPostOpsNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/FusedConvolutionWithPostOpNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/FusedDepthwiseConvolutionBatchNormalizationNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/GenerateProposalsLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/InputNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/L2NormalizeLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/NormalizationLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/NormalizePlanarYUVLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/OutputNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/PReluLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/PadLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/PermuteLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/PoolingLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/PrintLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/PriorBoxLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/QuantizationLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/ROIAlignLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/ReductionLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/ReorgLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/ReshapeLayer.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/ResizeLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/SliceLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/SoftmaxLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/SplitLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/StackLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/nodes/StridedSliceLayerNode.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/printers/DotGraphPrinter.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/backends/NEON/NEDeviceBackend.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/backends/NEON/NEFunctionFactory.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/backends/NEON/NENodeValidator.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/backends/NEON/NESubTensorHandle.os /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/src/graph/backends/NEON/NETensorHandle.os -L/arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty -L. -lpthread -ldl -larm_compute
arm-linux-gnueabihf-ar rc /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/libarm_compute_test_framework.a /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/DatasetModes.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/Exceptions.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/Framework.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/ParametersLibrary.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/Profiler.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/TestFilter.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/Utils.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/command_line/CommonOptions.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/printers/JSONPrinter.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/printers/PrettyPrinter.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/printers/Printer.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/printers/Printers.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/instruments/Instruments.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/instruments/InstrumentsStats.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/instruments/SchedulerTimer.o /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/instruments/WallClockTimer.o
arm-linux-gnueabihf-ranlib /arm_cpu_plugin/openvino/build/build-modules/arm_plugin/thirdparty/tests/framework/libarm_compute_test_framework.a
scons: done building targets.
[ 36%] Built target arm_compute_static_libs
make: *** [Makefile:163: all] Error 2
+ fail 12 OpenVINO build failed. Stopping
+ [ 2 -lt 2 ]
+ retval=12
+ shift
+ echo OpenVINO build failed. Stopping
OpenVINO build failed. Stopping
+ exit 12
```

openvino_contrib branch: master
openvino_contrib commit: 663dce6c73fe38a9bc7e02512807e5390c87db83

------

Thanks in advance!

**Comment by ilya-lavrenov** [comment]
Please, provide the actual error message. From the logs we can just see that build fails, but don't see the reason

**Comment by YaroslavSchubert** [comment]
oh, sorry, let me get back to you with the error message.

**Comment by YaroslavSchubert** [comment]
Error message:

```
Traceback (most recent call last):
  File "/arm_cpu_plugin/openvino/src/frontends/onnx/tests/onnx_prototxt_converter.py", line 26, in <module>
    import onnx
  File "/usr/local/lib/python3.7/site-packages/onnx/__init__.py", line 10, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
make[2]: *** [CMakeFiles/test_model_zoo.dir/build.make:825: ../bin/armv7l/Release/test_model_zoo/core/models/ir/add_abc.onnx] Error 1
make[1]: *** [CMakeFiles/Makefile2:145: CMakeFiles/test_model_zoo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by ilya-lavrenov** [comment]
Please, add `cmake -DENABLE_REQUIREMENTS_INSTALL=OFF` to other build options. 
We have to fix the behavior, thanks for the bug-report

**Comment by YaroslavSchubert** [comment]
I added   to `arm_cpu_plugin_build.sh` script like this
```
#Build OpenVINO                                                                                                                                                                                                    │···································································································
mkdir -p $OPENVINO_HOME/build && \                                                                                                                                                                                 │···································································································
cd $OPENVINO_HOME/build && \                                                                                                                                                                                       │···································································································
cmake -DOpenCV_DIR=$STAGING_DIR/extras/opencv/cmake -DENABLE_OPENCV=OFF \                                                                                                                                          │···································································································
      -DPYTHON_INCLUDE_DIRS="/opt/python3.7_arm/include/python3.7m" \                                                                                                                                              │···································································································
      -DPYTHON_LIBRARY="/opt/python3.7_arm/lib/libpython3.7m.so" \                                                                                                                                                 │···································································································
      -DENABLE_PYTHON=ON \                                                                                                                                                                                         │···································································································
      -DNGRAPH_PYTHON_BUILD_ENABLE=ON \                                                                                                                                                                            │···································································································
      -DNGRAPH_ONNX_IMPORT_ENABLE=ON \                                                                                                                                                                             │···································································································
      -DPYTHON_MODULE_EXTENSION=".so" \                                                                                                                                                                            │···································································································
      -DENABLE_TESTS=ON -DENABLE_FUNCTIONAL_TESTS=ON -DENABLE_GAPI_TESTS=OFF \                                                                                                                                     │···································································································
      -DENABLE_DATA=OFF \                                                                                                                                                                                          │···································································································      -DCMAKE_EXE_LINKER_FLAGS=-Wl,-rpath-link,$STAGING_DIR/opencv/lib \                                                                                                                                           │···································································································
      -DENABLE_MYRIAD=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE \                                                                                                                                                          │···································································································      -DTHREADING=SEQ -DENABLE_LTO=ON \                                                                                                                                                                            │···································································································
      -DCMAKE_TOOLCHAIN_FILE="$OPENVINO_HOME/cmake/$TOOLCHAIN_DEFS" \                                                                                                                                              │···································································································
      -DARM_COMPUTE_SCONS_JOBS=$BUILD_JOBS \                                                                                                                                                                       │···································································································
      -DIE_EXTRA_MODULES=$ARM_PLUGIN_HOME \                                                                                                                                                                        │···································································································
      -DENABLE_REQUIREMENTS_INSTALL=OFF \                                                                                                                                                                          │···································································································
      $OPENVINO_HOME && \                                                                                                                                                                                          │···································································································
make -j$BUILD_JOBS && \                                                                                                                                                                                            │···································································································
cmake -DCMAKE_INSTALL_PREFIX=$STAGING_DIR -P cmake_install.cmake && \                                                                                                                                              │···································································································
ARCHDIR=`ls $OPENVINO_HOME/bin` && \                                                                                                                                                                               │···································································································
cd $DEV_HOME || fail 12 "OpenVINO build failed. Stopping"
```
but still got the error.

Please, let me know if I'm doing something wrong.

**Comment by ilya-lavrenov** [comment]
Please, provide error message. 
The original error message should have gone.

**Comment by YaroslavSchubert** [comment]
```
Traceback (most recent call last):
  File "/arm_cpu_plugin/openvino/src/frontends/onnx/tests/onnx_prototxt_converter.py", line 24, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'
make[2]: *** [CMakeFiles/test_model_zoo.dir/build.make:825: ../bin/armv7l/Release/test_model_zoo/core/models/ir/add_abc.onnx] Error 1
make[1]: *** [CMakeFiles/Makefile2:144: CMakeFiles/test_model_zoo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by ilya-lavrenov** [comment]
Install requirements from file https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/requirements.txt:
```bash
python3 -m pip install -r src/frontends/onnx/tests/requirements.txt
```

**Comment by ilya-lavrenov** [comment]
I can suggest to turn of ONNX frontend using `-DENABLE_OV_ONNX_FRONTEND=OFF`
It turned out that ONNX is not available for armv7l (see https://pypi.org/project/onnx/1.11.0/#files), while OV build tries to use such module unconditionally.

**Comment by ilya-lavrenov** [comment]
UPDATE:
I had a look once again to the issue, since you are using cross-compilation - what is the architecture?
If it's x86_64 I suppose onnx can be installed.

In any case - there is a fix with check for ONNX first before its usage https://github.com/openvinotoolkit/openvino/pull/13069

**Comment by YaroslavSchubert** [comment]
Yes, it's x86_64.
Thank you.
