### ISSUE TITLE
arm_plugin RuntimeError: [ NOT_FOUND ] : PERFORMANCE_HINT

### ISSUE THREAD

**Issue by mzwtjp** [openvinotoolkit/openvino_contrib#472]
I am trying arm_plugin (branch releases/2022/2) on Jetson Nano and seeing this error.
This plugin is seen as "CPU" device, so I specified "-d CPU" to benchmark_app command line, and but it trminates with this error.

I am new to OpenVINO and its arm_plugin, so I am not sure if this error expected or anythong is wrong in my build.

Though it is not part of the core openvino distribution, I was seeing people using this on RPi so I expected I can use this on Jetson without hassle.

Any advice or hint is highly appreiated!

> $ benchmark_app -d CPU -m intel/yolo-v2-tiny-ava-0001/FP16/yolo-v2-tiny-ava-0001.xml
> [Step 1/11] Parsing and validating input arguments
> [ INFO ] Parsing input parameters
> [ INFO ] Input command: /usr/local/bin/benchmark_app -d CPU -m intel/yolo-v2-tiny-ava-0001/FP16/yolo-v2-tiny-ava-0001.xml
> [Step 2/11] Loading OpenVINO Runtime
> [ INFO ] OpenVINO:
> [ INFO ] Build ................................. 2022.3.0-8655-5ac06838cd8
> [ INFO ]
> [ INFO ] Device info:
> [ INFO ] CPU
> [ INFO ] Build ................................. 2022.3.0-8655-5ac06838cd8
> [ INFO ]
> [ INFO ]
> [Step 3/11] Setting device configuration
> [ WARNING ] Device CPU does not support performance hint property(-hint).
> [ WARNING ] -nstreams default value is determined automatically for CPU device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
> [ ERROR ] [ NOT_FOUND ] : PERFORMANCE_HINT
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/openvino/tools/benchmark/main.py", line 250, in main
>     benchmark.set_config(config)
>   File "/usr/local/lib/python3.6/dist-packages/openvino/tools/benchmark/benchmark.py", line 57, in set_config
>     self.core.set_property(device, config[device])
> RuntimeError: [ NOT_FOUND ] : PERFORMANCE_HINT
> $
> $

**Comment by mzwtjp** [comment]
Closing for now.

Just tried again building bits from 2022/2 branch.
As I can see, here lack of -hint support is reported as warning and does not terminate the benchmark_app.

> [Step 1/11] Parsing and validating input arguments
> [ WARNING ]  -nstreams default value is determined automatically for a device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
> [Step 2/11] Loading OpenVINO
> [ WARNING ] Device CPU does not support performance hint property(-hint).
> [ INFO ] OpenVINO:
>          API version............. 2022.2.0-000-4da2c945d6c-releases/2022/2
> [ INFO ] Device info
>          CPU
>          openvino_arm_cpu_plugin. version 2022.2
>          Build................... 2022.2.0-000-4da2c945d6c-releases/2022/2
> 
> [Step 3/11] Setting device configuration
> [ WARNING ] -nstreams default value is determined automatically for CPU device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
> [Step 4/11] Reading network files
> ...
