### ISSUE TITLE
Model failed to load on ARM CPU

### ISSUE THREAD

**Issue by Dev-Divyendh** [openvinotoolkit/openvino_contrib#624]
I am using a raspberry pi 4 with openvino 2022.1 on raspbian buster os, I tried following this link to build arm plugin:
[https://github.com/openvinotoolkit/openvino_contrib/wiki/How-to-build-ARM-CPU-plugin](https://github.com/openvinotoolkit/openvino_contrib/wiki/How-to-build-ARM-CPU-plugin)
I tried the third , native compilation method.
I cloned 'releases/2022/1' branch of openvino_contrib and used it.
I used open model zoo's object detection demo:
I ran yolo model using the following command:
python3 object_detection_demo.py -i ~/Downloads/person-bicycle-car-detection.mp4 -m ~/Downloads/person-vehicle-bike-detection-crossroad-yolov3-1020.xml -at yolo -d CPU

Got this error:
Traceback (most recent call last):
File "object_detection_demo.py", line 298, in
sys.exit(main() or 0)
File "object_detection_demo.py", line 183, in main
detector_pipeline = AsyncPipeline(model)
File "/home/pi/.local/lib/python3.7/site-packages/openvino/model_zoo/model_api/pipelines/async_pipeline.py", line 86, in init
self.model.load()
File "/home/pi/.local/lib/python3.7/site-packages/openvino/model_zoo/model_api/models/model.py", line 173, in load
self.model_adapter.load_model()
File "/home/pi/.local/lib/python3.7/site-packages/openvino/model_zoo/model_api/adapters/openvino_adapter.py", line 66, in load_model
self.async_queue = AsyncInferQueue(self.compiled_model, self.max_num_requests)
RuntimeError: std::bad_alloc

Kindly help resolve this issue.
Or is there a model specific for object detection model to run on arm cpu.

**Comment by Dev-Divyendh** [comment]
It worked with releases/2022/3. Thanks!
